### ISSUE TITLE
rewards_history

### ISSUE THREAD

**Issue by mushroom1116** [borgwang/reinforce_py#1]
`if not rewards_history:
            rewards_history.append(ep_rewards)
        else:
            rewards_history.append(
                rewards_history[-1] * 0.9 + ep_rewards * 0.1)`

What's meaning of this piece of code? It stores `rewards_history[-1] * 0.9 + ep_rewards * 0.1)` as the reward of this episode, why?

**Comment by borgwang** [comment]
@mushroom1116  Sorry for the late reply.
This piece of code is just a simple smoothing trick. `rewards_history` stores smoothed reward of each episode, which is calculated by `current smoothed reward = previous smoothed reward * 0.9 + current raw reward * 0.1`

**Comment by mushroom1116** [comment]
@borgwang Thanks for your replay. The `rewards_history` and `steps_history` are just for plotting, so the purpose of this trick is for smoothing the plots and have no effect on training result, right? Why not take the more straightforward actual `ep_rewards` in plotting?

**Comment by borgwang** [comment]
@mushroom1116  Plotting the raw rewards is fine too. Just for a better view.
